// Mocks generated by Mockito 5.4.6 from annotations
// in lista_paises/test/services/paises_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lista_paises/models/pais.dart' as _i4;
import 'package:lista_paises/services/ipaises_manager.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IPaisesManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPaisesManager extends _i1.Mock implements _i2.IPaisesManager {
  MockIPaisesManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Pais>> obterPaises() =>
      (super.noSuchMethod(
            Invocation.method(#obterPaises, []),
            returnValue: _i3.Future<List<_i4.Pais>>.value(<_i4.Pais>[]),
          )
          as _i3.Future<List<_i4.Pais>>);

  @override
  _i3.Future<List<_i4.Pais>> obterPaisesPorNome(String? nome) =>
      (super.noSuchMethod(
            Invocation.method(#obterPaisesPorNome, [nome]),
            returnValue: _i3.Future<List<_i4.Pais>>.value(<_i4.Pais>[]),
          )
          as _i3.Future<List<_i4.Pais>>);
}
